apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: file-watcher
  namespace: argo-events
spec:
  file:
    context-files:
      watchPathConfig:
        directory: /app/context
        eventType: "IN_CLOSE_WRITE"
        pathRegexp: ".*\\.(pdf|csv|json|md|xlsx)$"
