#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE keycloak;
    CREATE DATABASE marquez;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE marquez TO $POSTGRES_USER;
    CREATE USER marquez WITH PASSWORD 'marquez';
    GRANT ALL PRIVILEGES ON DATABASE marquez TO marquez;
    ALTER DATABASE marquez OWNER TO marquez;
EOSQL
