#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE argo;
    CREATE DATABASE keycloak;
    CREATE DATABASE marquez;
    GRANT ALL PRIVILEGES ON DATABASE argo TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE marquez TO $POSTGRES_USER;
EOSQL
