# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import a2a_pb2 as a2a__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in a2a_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """A2A Protocol Buffer Definitions
    Agent-to-Agent communication protocol

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/antigravity.a2a.AgentService/SubmitTask',
                request_serializer=a2a__pb2.TaskRequest.SerializeToString,
                response_deserializer=a2a__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/antigravity.a2a.AgentService/GetHealth',
                request_serializer=a2a__pb2.HealthRequest.SerializeToString,
                response_deserializer=a2a__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Handoff = channel.unary_unary(
                '/antigravity.a2a.AgentService/Handoff',
                request_serializer=a2a__pb2.HandoffRequest.SerializeToString,
                response_deserializer=a2a__pb2.HandoffResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """A2A Protocol Buffer Definitions
    Agent-to-Agent communication protocol

    """

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Handoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=a2a__pb2.TaskRequest.FromString,
                    response_serializer=a2a__pb2.TaskResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=a2a__pb2.HealthRequest.FromString,
                    response_serializer=a2a__pb2.HealthResponse.SerializeToString,
            ),
            'Handoff': grpc.unary_unary_rpc_method_handler(
                    servicer.Handoff,
                    request_deserializer=a2a__pb2.HandoffRequest.FromString,
                    response_serializer=a2a__pb2.HandoffResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antigravity.a2a.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antigravity.a2a.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """A2A Protocol Buffer Definitions
    Agent-to-Agent communication protocol

    """

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antigravity.a2a.AgentService/SubmitTask',
            a2a__pb2.TaskRequest.SerializeToString,
            a2a__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antigravity.a2a.AgentService/GetHealth',
            a2a__pb2.HealthRequest.SerializeToString,
            a2a__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Handoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antigravity.a2a.AgentService/Handoff',
            a2a__pb2.HandoffRequest.SerializeToString,
            a2a__pb2.HandoffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
