# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: a2a.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'a2a.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ta2a.proto\x12\x0f\x61ntigravity.a2a\"S\n\x0bTaskRequest\x12\x0c\n\x04goal\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\"B\n\x0cTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"M\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12+\n\x06levels\x18\x02 \x03(\x0b\x32\x1b.antigravity.a2a.LevelCheck\":\n\nLevelCheck\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07healthy\x18\x03 \x01(\x08\"J\n\x0eHandoffRequest\x12\x14\n\x0ctarget_agent\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\"1\n\x0fHandoffResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t2\xf5\x01\n\x0c\x41gentService\x12I\n\nSubmitTask\x12\x1c.antigravity.a2a.TaskRequest\x1a\x1d.antigravity.a2a.TaskResponse\x12L\n\tGetHealth\x12\x1e.antigravity.a2a.HealthRequest\x1a\x1f.antigravity.a2a.HealthResponse\x12L\n\x07Handoff\x12\x1f.antigravity.a2a.HandoffRequest\x1a .antigravity.a2a.HandoffResponseB\x11Z\x0f\x61ntigravity/a2ab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a2a_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017antigravity/a2a'
  _globals['_TASKREQUEST']._serialized_start=30
  _globals['_TASKREQUEST']._serialized_end=113
  _globals['_TASKRESPONSE']._serialized_start=115
  _globals['_TASKRESPONSE']._serialized_end=181
  _globals['_HEALTHREQUEST']._serialized_start=183
  _globals['_HEALTHREQUEST']._serialized_end=198
  _globals['_HEALTHRESPONSE']._serialized_start=200
  _globals['_HEALTHRESPONSE']._serialized_end=277
  _globals['_LEVELCHECK']._serialized_start=279
  _globals['_LEVELCHECK']._serialized_end=337
  _globals['_HANDOFFREQUEST']._serialized_start=339
  _globals['_HANDOFFREQUEST']._serialized_end=413
  _globals['_HANDOFFRESPONSE']._serialized_start=415
  _globals['_HANDOFFRESPONSE']._serialized_end=464
  _globals['_AGENTSERVICE']._serialized_start=467
  _globals['_AGENTSERVICE']._serialized_end=712
# @@protoc_insertion_point(module_scope)
