# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import superbuilder_pb2 as superbuilder__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in superbuilder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuperBuilderStub(object):
    """Intel SuperBuilder gRPC Definitions
    Maps Intel GUI requests to Goose agent execution

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteWorkflow = channel.unary_unary(
                '/antigravity.superbuilder.SuperBuilder/ExecuteWorkflow',
                request_serializer=superbuilder__pb2.WorkflowRequest.SerializeToString,
                response_deserializer=superbuilder__pb2.WorkflowResponse.FromString,
                _registered_method=True)
        self.GetWorkflowStatus = channel.unary_unary(
                '/antigravity.superbuilder.SuperBuilder/GetWorkflowStatus',
                request_serializer=superbuilder__pb2.StatusRequest.SerializeToString,
                response_deserializer=superbuilder__pb2.StatusResponse.FromString,
                _registered_method=True)


class SuperBuilderServicer(object):
    """Intel SuperBuilder gRPC Definitions
    Maps Intel GUI requests to Goose agent execution

    """

    def ExecuteWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuperBuilderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWorkflow,
                    request_deserializer=superbuilder__pb2.WorkflowRequest.FromString,
                    response_serializer=superbuilder__pb2.WorkflowResponse.SerializeToString,
            ),
            'GetWorkflowStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowStatus,
                    request_deserializer=superbuilder__pb2.StatusRequest.FromString,
                    response_serializer=superbuilder__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antigravity.superbuilder.SuperBuilder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antigravity.superbuilder.SuperBuilder', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuperBuilder(object):
    """Intel SuperBuilder gRPC Definitions
    Maps Intel GUI requests to Goose agent execution

    """

    @staticmethod
    def ExecuteWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antigravity.superbuilder.SuperBuilder/ExecuteWorkflow',
            superbuilder__pb2.WorkflowRequest.SerializeToString,
            superbuilder__pb2.WorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antigravity.superbuilder.SuperBuilder/GetWorkflowStatus',
            superbuilder__pb2.StatusRequest.SerializeToString,
            superbuilder__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
