# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: superbuilder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'superbuilder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12superbuilder.proto\x12\x18\x61ntigravity.superbuilder\"\xbd\x01\n\x0fWorkflowRequest\x12\x15\n\rworkflow_name\x18\x01 \x01(\t\x12M\n\nparameters\x18\x02 \x03(\x0b\x32\x39.antigravity.superbuilder.WorkflowRequest.ParametersEntry\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\x10WorkflowResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x0e\n\x06run_id\x18\x03 \x01(\t\"\x1f\n\rStatusRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"@\n\x0eStatusResponse\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\r\n\x05phase\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xe0\x01\n\x0cSuperBuilder\x12h\n\x0f\x45xecuteWorkflow\x12).antigravity.superbuilder.WorkflowRequest\x1a*.antigravity.superbuilder.WorkflowResponse\x12\x66\n\x11GetWorkflowStatus\x12\'.antigravity.superbuilder.StatusRequest\x1a(.antigravity.superbuilder.StatusResponseB\x1aZ\x18\x61ntigravity/superbuilderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'superbuilder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030antigravity/superbuilder'
  _globals['_WORKFLOWREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_WORKFLOWREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_WORKFLOWREQUEST']._serialized_start=49
  _globals['_WORKFLOWREQUEST']._serialized_end=238
  _globals['_WORKFLOWREQUEST_PARAMETERSENTRY']._serialized_start=189
  _globals['_WORKFLOWREQUEST_PARAMETERSENTRY']._serialized_end=238
  _globals['_WORKFLOWRESPONSE']._serialized_start=240
  _globals['_WORKFLOWRESPONSE']._serialized_end=308
  _globals['_STATUSREQUEST']._serialized_start=310
  _globals['_STATUSREQUEST']._serialized_end=341
  _globals['_STATUSRESPONSE']._serialized_start=343
  _globals['_STATUSRESPONSE']._serialized_end=407
  _globals['_SUPERBUILDER']._serialized_start=410
  _globals['_SUPERBUILDER']._serialized_end=634
# @@protoc_insertion_point(module_scope)
